import unittest
import string
import sys
import os

sys.path.insert(0, os.path.abspath('../sealant/randstr')) # Ughh
from randstr import RandomString
from randstr_terminal import RandstrParser

class RandomStringGeneration(unittest.TestCase):
    """Tests for RandomString class methods"""

    @property
    def default_case(self):
        """Default string generation for most unittest cases"""
        string_generator = RandomString(length=20)
        return string_generator()

    def test_generated_length(self):
        """String generated by providing only required arguments"""

        self.assertEqual(20, len(self.default_case))

    def test_default_char_set(self):
        """Verify correct default character set used"""
        char_set = ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVW"
        "XYZ0123456789!\"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~ ")

        self.assertEqual(RandomString().default_char_set, char_set)

    def test_char_set_override(self):
        """Verify user provided character set sticks"""
        char_set = "abcDEF123,.;"
        randstr_obj = RandomString(user_char_set=char_set)

        self.assertEqual(char_set, randstr_obj.char_set)

    def test_user_char_set_generation(self):
        """Verify only user_char_set characters are used for random string
        generation"""

        char_set = "abcDEF123,.;"
        for char_len in range(10, 101, 10):
            return_str = RandomString(length=char_len, user_char_set=char_set)
            with self.subTest(return_str=return_str, char_set=char_set):
                self.assertTrue(set(char_set).issuperset(set(return_str)))


if __name__ == '__main__':
    unittest.main()